# Generated by Django 5.2.11 on 2026-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("resolved", "Resolved"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField()),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Incident Message",
                "verbose_name_plural": "Incident Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("up", "Up"), ("down", "Down")], max_length=10
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("checked_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Health Check",
                "verbose_name_plural": "Health Checks",
                "ordering": ["-checked_at"],
                "get_latest_by": "checked_at",
                "indexes": [
                    models.Index(
                        fields=["service_name", "-checked_at"],
                        name="monitoring__service_80938b_idx",
                    ),
                    models.Index(
                        fields=["-checked_at"], name="monitoring__checked_55eb44_idx"
                    ),
                ],
            },
        ),
    ]
