# Generated by Django 5.2.11 on 2026-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_outage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('affected_services', models.TextField(blank=True, default='', help_text="Comma-separated service names exactly as in MONITORED_SERVICES (e.g. 'MCP Server, Linker'). Leave blank to cover all services.")),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to cancel this window without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Maintenance Window',
                'verbose_name_plural': 'Maintenance Windows',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['active', 'start_time', 'end_time'], name='monitoring__active_ea58c3_idx')],
            },
        ),
    ]
