# Generated by Django 5.2.11 on 2026-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional detail shown beneath the title on the status page.'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='end_time',
            field=models.DateTimeField(help_text='When the window ends (UTC).'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='start_time',
            field=models.DateTimeField(db_index=True, help_text="When the window begins (UTC). While now is between start and end, affected services show 'Under Maintenance' and their alerts are suppressed."),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='title',
            field=models.CharField(help_text="Short summary shown on the status page, e.g. 'Database upgrade'.", max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text="Uncheck (or use the 'mark resolved' action) to move this into history."),
        ),
        migrations.AlterField(
            model_name='message',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('resolved', 'Resolved')], help_text='High shows the banner as a Major Outage; Medium as Degraded Performance.', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='Shown verbatim on the public status page and in the RSS/Atom feed.'),
        ),
    ]
